/* Finrise admin data layer. Browser uses publishable key only; all reads/actions are authenticated and RLS/RPC protected. */
(function(){
 const url=window.FINRISE_SUPABASE_URL||'https://jdcqczgrgnlqfzfgnsog.supabase.co';
 const key=window.FINRISE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_C1cHus8zHeSRzWEnQn0kiA_c4m45QH9';
 if(!window.supabase){console.error('Supabase JS did not load');return}
 const db=window.finriseAdminClient=window.supabase.createClient(url,key);
 const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:2});
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const notify=m=>typeof window.showToast==='function'?window.showToast(m):alert(m);
 async function ensureAdmin(){const {data:{session},error}=await db.auth.getSession();if(error||!session){location.replace('admin-login.html');return null}const {data:role,error:re}=await db.from('admin_roles').select('role').eq('user_id',session.user.id).maybeSingle();if(re||!role){await db.auth.signOut();location.replace('admin-login.html');return null}return session.user}
 async function api(action,payload={}){const {data:{session}}=await db.auth.getSession();if(!session)throw new Error('Session expired. Sign in again.');const {data,error}=await db.functions.invoke('finrise-admin-api',{body:{action,...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
 async function load(){const user=await ensureAdmin();if(!user)return;try{const data=await api('overview');setText('totalUsers',data.stats.users.toLocaleString());setText('totalDeposits',money(data.stats.depositTotal));const stats=document.querySelectorAll('#dashboard .stat-card .stat-value');if(stats[2])stats[2].textContent=money(data.stats.withdrawalTotal);if(stats[3])stats[3].textContent=money(data.stats.investedTotal);renderTable('usersTable',data.users, userRow);renderTable('depositsTable',data.deposits,depositRow);renderTable('withdrawalsTable',data.withdrawals,withdrawalRow);renderTable('activeTable',data.investments,investmentRow);renderTable('transactionsTable',data.ledger,ledgerRow);renderTable('adminAuditTable',data.audit||[],auditRow);setText('depositBadge',data.stats.pendingDeposits);setText('withdrawalBadge',data.stats.pendingWithdrawals);renderPending(data.deposits,data.withdrawals);renderActivities(data.activity||[]);notify('Live data loaded from Supabase.')}catch(e){console.error(e);notify('Could not load live admin data: '+(e.message||e));}}
 function setText(id,v){const el=document.getElementById(id);if(el)el.textContent=v}
 function renderTable(id,rows,rowFn){const t=document.querySelector('#'+id+' tbody');if(!t)return;t.innerHTML=rows?.length?rows.map(rowFn).join(''):'<tr><td colspan="9"><div class="empty-state">No records found.</div></td></tr>'}
 function userRow(x){return `<tr><td>${esc(x.full_name||'User')}</td><td>${esc(x.email||'—')}</td><td>${money(x.available_balance)}</td><td>${money(x.invested)}</td><td>${Number(x.referrals||0)}</td><td><span class="status active">Active</span></td><td><button class="small-btn" onclick="window.finriseAdmin.viewUser('${esc(x.id)}')"><i class="fa-solid fa-eye"></i></button></td></tr>`}
 function status(s){const v=String(s||'pending').toLowerCase();return `<span class="status ${esc(v)}">${esc(v)}</span>`}
 function depositRow(x){return `<tr><td>${esc(x.full_name||x.user_id)}</td><td>${money(x.amount)}</td><td>${esc(x.method||'')}</td><td>${esc(x.reference||x.id)}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td><td>${status(x.status)}</td><td><div class="actions">${x.status==='pending'?`<button class="small-btn approve" onclick="window.finriseAdmin.decide('deposit','approve','${x.id}')">✓</button><button class="small-btn reject" onclick="window.finriseAdmin.decide('deposit','reject','${x.id}')">×</button>`:''}<button class="small-btn" onclick="window.finriseAdmin.viewRecord('${esc(x.id)}')">i</button></div></td></tr>`}
 function withdrawalRow(x){return `<tr><td>${esc(x.full_name||x.user_id)}</td><td>${money(x.amount)}</td><td>${esc(x.method||'')}</td><td>${esc(x.id)}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td><td>${status(x.status)}</td><td><div class="actions">${['pending','processing'].includes(x.status)?`<button class="small-btn approve" onclick="window.finriseAdmin.decide('withdrawal','complete','${x.id}')">✓</button><button class="small-btn reject" onclick="window.finriseAdmin.decide('withdrawal','reject','${x.id}')">×</button>`:''}</div></td></tr>`}
 function investmentRow(x){return `<tr><td>${esc(x.full_name||x.user_id)}</td><td>${esc(x.plan_name||'Plan')}</td><td>${money(x.principal)}</td><td>${money(x.expected_return)}</td><td>—</td><td>${esc(x.matures_at?new Date(x.matures_at).toLocaleDateString():'—')}</td><td>${status(x.status)}</td></tr>`}
 function ledgerRow(x){return `<tr><td>${esc(x.id)}</td><td>${esc(x.full_name||x.user_id)}</td><td>${esc(x.entry_type)}</td><td>${money(x.amount)}</td><td>${esc(x.reference_type||'record')}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td></tr>`}
 function auditRow(x){return `<tr><td>${esc(x.actor_id||'—')}</td><td>${esc(x.action)}</td><td>${esc(x.target_type||'—')}</td><td>${esc(JSON.stringify(x.metadata||{}))}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td></tr>`}
 function renderPending(ds,ws){const t=document.querySelector('#pendingTable tbody');if(!t)return;const all=[...(ds||[]).filter(x=>x.status==='pending').map(x=>({...x,_type:'deposit'})),...(ws||[]).filter(x=>x.status==='pending').map(x=>({...x,_type:'withdrawal'}))].slice(0,30);t.innerHTML=all.length?all.map(x=>`<tr><td>${esc(x.full_name||x.user_id)}</td><td>${x._type}</td><td>${money(x.amount)}</td><td>${esc(x.reference||x.id)}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td><td>${status(x.status)}</td><td><div class="actions"><button class="small-btn approve" onclick="window.finriseAdmin.decide('${x._type}','${x._type==='deposit'?'approve':'complete'}','${x.id}')">✓</button><button class="small-btn reject" onclick="window.finriseAdmin.decide('${x._type}','reject','${x.id}')">×</button></div></td></tr>`).join(''):'<tr><td colspan="7">No pending transactions.</td></tr>'}
 function renderActivities(a){const el=document.getElementById('activityList');if(!el)return;el.innerHTML=a.length?a.slice(0,8).map(x=>`<div class="activity-item"><div class="activity-icon"><i class="fa-solid fa-clock"></i></div><div class="activity-info"><strong>${esc(x.action||x.entry_type||'Activity')}</strong><span>${esc(new Date(x.created_at).toLocaleString())}</span></div><div class="activity-amount">${x.amount!=null?money(x.amount):''}</div></div>`).join(''):'<div class="empty-state">No recent activity.</div>'}
 async function decide(type,decision,id){const reason=decision==='reject'?prompt('Enter a rejection reason for the audit record:'):'';if(decision==='reject'&&!reason?.trim())return;if(!confirm(`${decision} this ${type} request?`))return;try{await api('transaction-action',{type,decision,id,reason});notify('Action completed successfully.');await load()}catch(e){notify('Action failed: '+(e.message||e))}}
 window.finriseAdmin={reload:load,decide,viewUser:id=>notify('User ID: '+id),viewRecord:id=>notify('Record ID: '+id)};
 window.refreshDashboard=()=>load();window.logout=async()=>{if(!confirm('Sign out of the admin panel?'))return;await db.auth.signOut();location.replace('admin-login.html')};
 document.addEventListener('DOMContentLoaded',()=>{load();const original=window.openSection;window.openSection=function(name){if(original)original(name);if(name==='settings')loadSettings()};});
 async function loadSettings(){try{const d=await api('settings-get');if(d.settings){const n=document.getElementById('platformName');if(n)n.value=d.settings.platform_name||'Finriseassets'}}catch(e){console.warn('Settings unavailable until migration is applied',e)}}
})();